---
- name: Setup development environment for Wujie EDI platform
  hosts: all
  remote_user: vagrant
  sudo: yes

  roles:
    - role: geerlingguy.java
      java_packages:
        - java-1.8.0-openjdk
    - role: geerlingguy.mysql
    - role: geerlingguy.nginx
    - role: Stouts.rabbitmq
    - role: geerlingguy.jenkins

  vars:
    mysql_databases:
      - name: wujie
    mysql_users:
      - name: wujie
        host: "%"
        password: wujie
        priv: "wujie.*:ALL"



