# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code for communication between different systems', max_length=128, verbose_name='code')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('code',)]),
        ),
    ]
