# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-21 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=64, verbose_name='name')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code for communication between different systems', max_length=128, verbose_name='code')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('params_meta', jsonfield.fields.JSONField(help_text='JSON object for detailing service params')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(help_text='Step seq for a detail process', verbose_name='seq')),
                ('params_value', jsonfield.fields.JSONCharField(help_text='JSON object for storing service params value', max_length=4096)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Process')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Service')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together=set([('code',)]),
        ),
        migrations.AddField(
            model_name='process',
            name='services',
            field=models.ManyToManyField(through='task.Step', to='task.Service'),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('process', 'service', 'seq')]),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('customer', 'name')]),
        ),
    ]
