# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-04 07:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='params_meta',
        ),
        migrations.AddField(
            model_name='service',
            name='params_schema',
            field=jsonfield.fields.JSONField(default='', help_text='JSON schema for detailing service params'),
            preserve_default=False,
        ),
    ]
