# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_meta_to_schema'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('process', 'seq')]),
        ),
    ]
