# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_step_unique_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='interval',
            field=models.PositiveIntegerField(default=300, verbose_name='interval'),
        ),
    ]
