# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 18:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_add_content_type_2_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.RemoveField(
            model_name='process',
            name='services',
        ),
        migrations.RemoveField(
            model_name='step',
            name='params_value',
        ),
        migrations.RemoveField(
            model_name='step',
            name='service',
        ),
    ]
