# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('task', '0001_initial'), ('task', '0002_rename_meta_to_schema'), ('task', '0003_step_unique_key'), ('task', '0004_process_interval'), ('task', '0005_add_content_type_2_step'), ('task', '0006_remove_service_n_params_values')]

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=64, verbose_name='name')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customer')),
                ('interval', models.PositiveIntegerField(default=300, verbose_name='interval')),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.SmallIntegerField(help_text='Step seq for a detail process', verbose_name='seq')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.Process')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('object_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('process', 'seq')]),
        ),
        migrations.AlterUniqueTogether(
            name='process',
            unique_together=set([('customer', 'name')]),
        ),
    ]
