package com.wjelogistics.edi.esb.model.dao;

import com.wjelogistics.edi.esb.model.entity.CtnInfo;
import com.wjelogistics.edi.esb.model.entity.CtnInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;


public interface CtnInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	long countByExample(CtnInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int deleteByExample(CtnInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int insert(CtnInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int insertSelective(CtnInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	List<CtnInfo> selectByExample(CtnInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	CtnInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int updateByExampleSelective(@Param("record") CtnInfo record, @Param("example") CtnInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int updateByExample(@Param("record") CtnInfo record, @Param("example") CtnInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int updateByPrimaryKeySelective(CtnInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	int updateByPrimaryKey(CtnInfo record);
}