package com.wjelogistics.edi.esb.model.dao;

import com.wjelogistics.edi.esb.model.entity.CtnStatus;
import com.wjelogistics.edi.esb.model.entity.CtnStatusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtnStatusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    long countByExample(CtnStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int deleteByExample(CtnStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int insert(CtnStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int insertSelective(CtnStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    List<CtnStatus> selectByExample(CtnStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    CtnStatus selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int updateByExampleSelective(@Param("record") CtnStatus record, @Param("example") CtnStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int updateByExample(@Param("record") CtnStatus record, @Param("example") CtnStatusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int updateByPrimaryKeySelective(CtnStatus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    int updateByPrimaryKey(CtnStatus record);
}