package com.wjelogistics.edi.esb.model.dao;

import com.wjelogistics.edi.esb.model.entity.DatResult;
import com.wjelogistics.edi.esb.model.entity.DatResultExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface DatResultMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    long countByExample(DatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int deleteByExample(DatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int insert(DatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int insertSelective(DatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    List<DatResult> selectByExample(DatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    DatResult selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int updateByExampleSelective(@Param("record") DatResult record, @Param("example") DatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int updateByExample(@Param("record") DatResult record, @Param("example") DatResultExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int updateByPrimaryKeySelective(DatResult record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    int updateByPrimaryKey(DatResult record);
}