package com.wjelogistics.edi.esb.model.entity;

public class CtnInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_owner
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnOwner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_size_type
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnSizeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_seal_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnSealNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_num
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_measure
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnMeasure;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.truck_list
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String truckList;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.gate_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String gateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.dock_passtime
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String dockPasstime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.dl_port
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String dlPort;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.work_terminal
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String workTerminal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.suitcase_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String suitcaseTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.suitcase_site
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String suitcaseSite;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.vgm_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String vgmWeight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.vgm_result_code
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String vgmResultCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.vgm_reuslt_desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String vgmReusltDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_info.vessel_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String vesselInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.id
     *
     * @return the value of ctn_info.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.id
     *
     * @param id the value for ctn_info.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_no
     *
     * @return the value of ctn_info.ctn_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnNo() {
        return ctnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_no
     *
     * @param ctnNo the value for ctn_info.ctn_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnNo(String ctnNo) {
        this.ctnNo = ctnNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_owner
     *
     * @return the value of ctn_info.ctn_owner
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnOwner() {
        return ctnOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_owner
     *
     * @param ctnOwner the value for ctn_info.ctn_owner
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnOwner(String ctnOwner) {
        this.ctnOwner = ctnOwner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_size_type
     *
     * @return the value of ctn_info.ctn_size_type
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnSizeType() {
        return ctnSizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_size_type
     *
     * @param ctnSizeType the value for ctn_info.ctn_size_type
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnSizeType(String ctnSizeType) {
        this.ctnSizeType = ctnSizeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_seal_no
     *
     * @return the value of ctn_info.ctn_seal_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnSealNo() {
        return ctnSealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_seal_no
     *
     * @param ctnSealNo the value for ctn_info.ctn_seal_no
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnSealNo(String ctnSealNo) {
        this.ctnSealNo = ctnSealNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_num
     *
     * @return the value of ctn_info.ctn_num
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnNum() {
        return ctnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_num
     *
     * @param ctnNum the value for ctn_info.ctn_num
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnNum(String ctnNum) {
        this.ctnNum = ctnNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_weight
     *
     * @return the value of ctn_info.ctn_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnWeight() {
        return ctnWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_weight
     *
     * @param ctnWeight the value for ctn_info.ctn_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnWeight(String ctnWeight) {
        this.ctnWeight = ctnWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_measure
     *
     * @return the value of ctn_info.ctn_measure
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnMeasure() {
        return ctnMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_measure
     *
     * @param ctnMeasure the value for ctn_info.ctn_measure
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnMeasure(String ctnMeasure) {
        this.ctnMeasure = ctnMeasure;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.ctn_status
     *
     * @return the value of ctn_info.ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnStatus() {
        return ctnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.ctn_status
     *
     * @param ctnStatus the value for ctn_info.ctn_status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnStatus(String ctnStatus) {
        this.ctnStatus = ctnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.truck_list
     *
     * @return the value of ctn_info.truck_list
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getTruckList() {
        return truckList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.truck_list
     *
     * @param truckList the value for ctn_info.truck_list
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setTruckList(String truckList) {
        this.truckList = truckList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.gate_time
     *
     * @return the value of ctn_info.gate_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getGateTime() {
        return gateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.gate_time
     *
     * @param gateTime the value for ctn_info.gate_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setGateTime(String gateTime) {
        this.gateTime = gateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.dock_passtime
     *
     * @return the value of ctn_info.dock_passtime
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getDockPasstime() {
        return dockPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.dock_passtime
     *
     * @param dockPasstime the value for ctn_info.dock_passtime
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setDockPasstime(String dockPasstime) {
        this.dockPasstime = dockPasstime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.dl_port
     *
     * @return the value of ctn_info.dl_port
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getDlPort() {
        return dlPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.dl_port
     *
     * @param dlPort the value for ctn_info.dl_port
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setDlPort(String dlPort) {
        this.dlPort = dlPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.work_terminal
     *
     * @return the value of ctn_info.work_terminal
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getWorkTerminal() {
        return workTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.work_terminal
     *
     * @param workTerminal the value for ctn_info.work_terminal
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setWorkTerminal(String workTerminal) {
        this.workTerminal = workTerminal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.suitcase_time
     *
     * @return the value of ctn_info.suitcase_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getSuitcaseTime() {
        return suitcaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.suitcase_time
     *
     * @param suitcaseTime the value for ctn_info.suitcase_time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setSuitcaseTime(String suitcaseTime) {
        this.suitcaseTime = suitcaseTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.suitcase_site
     *
     * @return the value of ctn_info.suitcase_site
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getSuitcaseSite() {
        return suitcaseSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.suitcase_site
     *
     * @param suitcaseSite the value for ctn_info.suitcase_site
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setSuitcaseSite(String suitcaseSite) {
        this.suitcaseSite = suitcaseSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.vgm_weight
     *
     * @return the value of ctn_info.vgm_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getVgmWeight() {
        return vgmWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.vgm_weight
     *
     * @param vgmWeight the value for ctn_info.vgm_weight
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setVgmWeight(String vgmWeight) {
        this.vgmWeight = vgmWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.vgm_result_code
     *
     * @return the value of ctn_info.vgm_result_code
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getVgmResultCode() {
        return vgmResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.vgm_result_code
     *
     * @param vgmResultCode the value for ctn_info.vgm_result_code
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setVgmResultCode(String vgmResultCode) {
        this.vgmResultCode = vgmResultCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.vgm_reuslt_desc
     *
     * @return the value of ctn_info.vgm_reuslt_desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getVgmReusltDesc() {
        return vgmReusltDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.vgm_reuslt_desc
     *
     * @param vgmReusltDesc the value for ctn_info.vgm_reuslt_desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setVgmReusltDesc(String vgmReusltDesc) {
        this.vgmReusltDesc = vgmReusltDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_info.vessel_info_id
     *
     * @return the value of ctn_info.vessel_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getVesselInfoId() {
        return vesselInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_info.vessel_info_id
     *
     * @param vesselInfoId the value for ctn_info.vessel_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setVesselInfoId(String vesselInfoId) {
        this.vesselInfoId = vesselInfoId;
    }
}