package com.wjelogistics.edi.esb.model.entity;

import java.util.ArrayList;
import java.util.List;

public class CtnInfoExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public CtnInfoExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andCtnNoIsNull() {
			addCriterion("ctn_no is null");
			return (Criteria) this;
		}

		public Criteria andCtnNoIsNotNull() {
			addCriterion("ctn_no is not null");
			return (Criteria) this;
		}

		public Criteria andCtnNoEqualTo(String value) {
			addCriterion("ctn_no =", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoNotEqualTo(String value) {
			addCriterion("ctn_no <>", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoGreaterThan(String value) {
			addCriterion("ctn_no >", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_no >=", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoLessThan(String value) {
			addCriterion("ctn_no <", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoLessThanOrEqualTo(String value) {
			addCriterion("ctn_no <=", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoLike(String value) {
			addCriterion("ctn_no like", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoNotLike(String value) {
			addCriterion("ctn_no not like", value, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoIn(List<String> values) {
			addCriterion("ctn_no in", values, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoNotIn(List<String> values) {
			addCriterion("ctn_no not in", values, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoBetween(String value1, String value2) {
			addCriterion("ctn_no between", value1, value2, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnNoNotBetween(String value1, String value2) {
			addCriterion("ctn_no not between", value1, value2, "ctnNo");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerIsNull() {
			addCriterion("ctn_owner is null");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerIsNotNull() {
			addCriterion("ctn_owner is not null");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerEqualTo(String value) {
			addCriterion("ctn_owner =", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerNotEqualTo(String value) {
			addCriterion("ctn_owner <>", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerGreaterThan(String value) {
			addCriterion("ctn_owner >", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_owner >=", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerLessThan(String value) {
			addCriterion("ctn_owner <", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerLessThanOrEqualTo(String value) {
			addCriterion("ctn_owner <=", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerLike(String value) {
			addCriterion("ctn_owner like", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerNotLike(String value) {
			addCriterion("ctn_owner not like", value, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerIn(List<String> values) {
			addCriterion("ctn_owner in", values, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerNotIn(List<String> values) {
			addCriterion("ctn_owner not in", values, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerBetween(String value1, String value2) {
			addCriterion("ctn_owner between", value1, value2, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnOwnerNotBetween(String value1, String value2) {
			addCriterion("ctn_owner not between", value1, value2, "ctnOwner");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeIsNull() {
			addCriterion("ctn_sizetype is null");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeIsNotNull() {
			addCriterion("ctn_sizetype is not null");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeEqualTo(String value) {
			addCriterion("ctn_sizetype =", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeNotEqualTo(String value) {
			addCriterion("ctn_sizetype <>", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeGreaterThan(String value) {
			addCriterion("ctn_sizetype >", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_sizetype >=", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeLessThan(String value) {
			addCriterion("ctn_sizetype <", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeLessThanOrEqualTo(String value) {
			addCriterion("ctn_sizetype <=", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeLike(String value) {
			addCriterion("ctn_sizetype like", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeNotLike(String value) {
			addCriterion("ctn_sizetype not like", value, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeIn(List<String> values) {
			addCriterion("ctn_sizetype in", values, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeNotIn(List<String> values) {
			addCriterion("ctn_sizetype not in", values, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeBetween(String value1, String value2) {
			addCriterion("ctn_sizetype between", value1, value2, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSizetypeNotBetween(String value1, String value2) {
			addCriterion("ctn_sizetype not between", value1, value2, "ctnSizetype");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoIsNull() {
			addCriterion("ctn_sealno is null");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoIsNotNull() {
			addCriterion("ctn_sealno is not null");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoEqualTo(String value) {
			addCriterion("ctn_sealno =", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoNotEqualTo(String value) {
			addCriterion("ctn_sealno <>", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoGreaterThan(String value) {
			addCriterion("ctn_sealno >", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_sealno >=", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoLessThan(String value) {
			addCriterion("ctn_sealno <", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoLessThanOrEqualTo(String value) {
			addCriterion("ctn_sealno <=", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoLike(String value) {
			addCriterion("ctn_sealno like", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoNotLike(String value) {
			addCriterion("ctn_sealno not like", value, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoIn(List<String> values) {
			addCriterion("ctn_sealno in", values, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoNotIn(List<String> values) {
			addCriterion("ctn_sealno not in", values, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoBetween(String value1, String value2) {
			addCriterion("ctn_sealno between", value1, value2, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnSealnoNotBetween(String value1, String value2) {
			addCriterion("ctn_sealno not between", value1, value2, "ctnSealno");
			return (Criteria) this;
		}

		public Criteria andCtnNumIsNull() {
			addCriterion("ctn_num is null");
			return (Criteria) this;
		}

		public Criteria andCtnNumIsNotNull() {
			addCriterion("ctn_num is not null");
			return (Criteria) this;
		}

		public Criteria andCtnNumEqualTo(String value) {
			addCriterion("ctn_num =", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumNotEqualTo(String value) {
			addCriterion("ctn_num <>", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumGreaterThan(String value) {
			addCriterion("ctn_num >", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_num >=", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumLessThan(String value) {
			addCriterion("ctn_num <", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumLessThanOrEqualTo(String value) {
			addCriterion("ctn_num <=", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumLike(String value) {
			addCriterion("ctn_num like", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumNotLike(String value) {
			addCriterion("ctn_num not like", value, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumIn(List<String> values) {
			addCriterion("ctn_num in", values, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumNotIn(List<String> values) {
			addCriterion("ctn_num not in", values, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumBetween(String value1, String value2) {
			addCriterion("ctn_num between", value1, value2, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnNumNotBetween(String value1, String value2) {
			addCriterion("ctn_num not between", value1, value2, "ctnNum");
			return (Criteria) this;
		}

		public Criteria andCtnWeightIsNull() {
			addCriterion("ctn_weight is null");
			return (Criteria) this;
		}

		public Criteria andCtnWeightIsNotNull() {
			addCriterion("ctn_weight is not null");
			return (Criteria) this;
		}

		public Criteria andCtnWeightEqualTo(String value) {
			addCriterion("ctn_weight =", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightNotEqualTo(String value) {
			addCriterion("ctn_weight <>", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightGreaterThan(String value) {
			addCriterion("ctn_weight >", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_weight >=", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightLessThan(String value) {
			addCriterion("ctn_weight <", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightLessThanOrEqualTo(String value) {
			addCriterion("ctn_weight <=", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightLike(String value) {
			addCriterion("ctn_weight like", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightNotLike(String value) {
			addCriterion("ctn_weight not like", value, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightIn(List<String> values) {
			addCriterion("ctn_weight in", values, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightNotIn(List<String> values) {
			addCriterion("ctn_weight not in", values, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightBetween(String value1, String value2) {
			addCriterion("ctn_weight between", value1, value2, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnWeightNotBetween(String value1, String value2) {
			addCriterion("ctn_weight not between", value1, value2, "ctnWeight");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureIsNull() {
			addCriterion("ctn_measure is null");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureIsNotNull() {
			addCriterion("ctn_measure is not null");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureEqualTo(String value) {
			addCriterion("ctn_measure =", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureNotEqualTo(String value) {
			addCriterion("ctn_measure <>", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureGreaterThan(String value) {
			addCriterion("ctn_measure >", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_measure >=", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureLessThan(String value) {
			addCriterion("ctn_measure <", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureLessThanOrEqualTo(String value) {
			addCriterion("ctn_measure <=", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureLike(String value) {
			addCriterion("ctn_measure like", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureNotLike(String value) {
			addCriterion("ctn_measure not like", value, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureIn(List<String> values) {
			addCriterion("ctn_measure in", values, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureNotIn(List<String> values) {
			addCriterion("ctn_measure not in", values, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureBetween(String value1, String value2) {
			addCriterion("ctn_measure between", value1, value2, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnMeasureNotBetween(String value1, String value2) {
			addCriterion("ctn_measure not between", value1, value2, "ctnMeasure");
			return (Criteria) this;
		}

		public Criteria andCtnStatusIsNull() {
			addCriterion("ctn_status is null");
			return (Criteria) this;
		}

		public Criteria andCtnStatusIsNotNull() {
			addCriterion("ctn_status is not null");
			return (Criteria) this;
		}

		public Criteria andCtnStatusEqualTo(String value) {
			addCriterion("ctn_status =", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusNotEqualTo(String value) {
			addCriterion("ctn_status <>", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusGreaterThan(String value) {
			addCriterion("ctn_status >", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_status >=", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusLessThan(String value) {
			addCriterion("ctn_status <", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusLessThanOrEqualTo(String value) {
			addCriterion("ctn_status <=", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusLike(String value) {
			addCriterion("ctn_status like", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusNotLike(String value) {
			addCriterion("ctn_status not like", value, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusIn(List<String> values) {
			addCriterion("ctn_status in", values, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusNotIn(List<String> values) {
			addCriterion("ctn_status not in", values, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusBetween(String value1, String value2) {
			addCriterion("ctn_status between", value1, value2, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andCtnStatusNotBetween(String value1, String value2) {
			addCriterion("ctn_status not between", value1, value2, "ctnStatus");
			return (Criteria) this;
		}

		public Criteria andTruckLisIsNull() {
			addCriterion("truck_lis is null");
			return (Criteria) this;
		}

		public Criteria andTruckLisIsNotNull() {
			addCriterion("truck_lis is not null");
			return (Criteria) this;
		}

		public Criteria andTruckLisEqualTo(String value) {
			addCriterion("truck_lis =", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisNotEqualTo(String value) {
			addCriterion("truck_lis <>", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisGreaterThan(String value) {
			addCriterion("truck_lis >", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisGreaterThanOrEqualTo(String value) {
			addCriterion("truck_lis >=", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisLessThan(String value) {
			addCriterion("truck_lis <", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisLessThanOrEqualTo(String value) {
			addCriterion("truck_lis <=", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisLike(String value) {
			addCriterion("truck_lis like", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisNotLike(String value) {
			addCriterion("truck_lis not like", value, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisIn(List<String> values) {
			addCriterion("truck_lis in", values, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisNotIn(List<String> values) {
			addCriterion("truck_lis not in", values, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisBetween(String value1, String value2) {
			addCriterion("truck_lis between", value1, value2, "truckLis");
			return (Criteria) this;
		}

		public Criteria andTruckLisNotBetween(String value1, String value2) {
			addCriterion("truck_lis not between", value1, value2, "truckLis");
			return (Criteria) this;
		}

		public Criteria andGateTimeIsNull() {
			addCriterion("gate_time is null");
			return (Criteria) this;
		}

		public Criteria andGateTimeIsNotNull() {
			addCriterion("gate_time is not null");
			return (Criteria) this;
		}

		public Criteria andGateTimeEqualTo(String value) {
			addCriterion("gate_time =", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeNotEqualTo(String value) {
			addCriterion("gate_time <>", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeGreaterThan(String value) {
			addCriterion("gate_time >", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeGreaterThanOrEqualTo(String value) {
			addCriterion("gate_time >=", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeLessThan(String value) {
			addCriterion("gate_time <", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeLessThanOrEqualTo(String value) {
			addCriterion("gate_time <=", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeLike(String value) {
			addCriterion("gate_time like", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeNotLike(String value) {
			addCriterion("gate_time not like", value, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeIn(List<String> values) {
			addCriterion("gate_time in", values, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeNotIn(List<String> values) {
			addCriterion("gate_time not in", values, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeBetween(String value1, String value2) {
			addCriterion("gate_time between", value1, value2, "gateTime");
			return (Criteria) this;
		}

		public Criteria andGateTimeNotBetween(String value1, String value2) {
			addCriterion("gate_time not between", value1, value2, "gateTime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeIsNull() {
			addCriterion("dock_passtime is null");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeIsNotNull() {
			addCriterion("dock_passtime is not null");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeEqualTo(String value) {
			addCriterion("dock_passtime =", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeNotEqualTo(String value) {
			addCriterion("dock_passtime <>", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeGreaterThan(String value) {
			addCriterion("dock_passtime >", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeGreaterThanOrEqualTo(String value) {
			addCriterion("dock_passtime >=", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeLessThan(String value) {
			addCriterion("dock_passtime <", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeLessThanOrEqualTo(String value) {
			addCriterion("dock_passtime <=", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeLike(String value) {
			addCriterion("dock_passtime like", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeNotLike(String value) {
			addCriterion("dock_passtime not like", value, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeIn(List<String> values) {
			addCriterion("dock_passtime in", values, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeNotIn(List<String> values) {
			addCriterion("dock_passtime not in", values, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeBetween(String value1, String value2) {
			addCriterion("dock_passtime between", value1, value2, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDockPasstimeNotBetween(String value1, String value2) {
			addCriterion("dock_passtime not between", value1, value2, "dockPasstime");
			return (Criteria) this;
		}

		public Criteria andDlPortIsNull() {
			addCriterion("dl_port is null");
			return (Criteria) this;
		}

		public Criteria andDlPortIsNotNull() {
			addCriterion("dl_port is not null");
			return (Criteria) this;
		}

		public Criteria andDlPortEqualTo(String value) {
			addCriterion("dl_port =", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortNotEqualTo(String value) {
			addCriterion("dl_port <>", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortGreaterThan(String value) {
			addCriterion("dl_port >", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortGreaterThanOrEqualTo(String value) {
			addCriterion("dl_port >=", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortLessThan(String value) {
			addCriterion("dl_port <", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortLessThanOrEqualTo(String value) {
			addCriterion("dl_port <=", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortLike(String value) {
			addCriterion("dl_port like", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortNotLike(String value) {
			addCriterion("dl_port not like", value, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortIn(List<String> values) {
			addCriterion("dl_port in", values, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortNotIn(List<String> values) {
			addCriterion("dl_port not in", values, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortBetween(String value1, String value2) {
			addCriterion("dl_port between", value1, value2, "dlPort");
			return (Criteria) this;
		}

		public Criteria andDlPortNotBetween(String value1, String value2) {
			addCriterion("dl_port not between", value1, value2, "dlPort");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalIsNull() {
			addCriterion("work_terminal is null");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalIsNotNull() {
			addCriterion("work_terminal is not null");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalEqualTo(String value) {
			addCriterion("work_terminal =", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalNotEqualTo(String value) {
			addCriterion("work_terminal <>", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalGreaterThan(String value) {
			addCriterion("work_terminal >", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalGreaterThanOrEqualTo(String value) {
			addCriterion("work_terminal >=", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalLessThan(String value) {
			addCriterion("work_terminal <", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalLessThanOrEqualTo(String value) {
			addCriterion("work_terminal <=", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalLike(String value) {
			addCriterion("work_terminal like", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalNotLike(String value) {
			addCriterion("work_terminal not like", value, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalIn(List<String> values) {
			addCriterion("work_terminal in", values, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalNotIn(List<String> values) {
			addCriterion("work_terminal not in", values, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalBetween(String value1, String value2) {
			addCriterion("work_terminal between", value1, value2, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andWorkTerminalNotBetween(String value1, String value2) {
			addCriterion("work_terminal not between", value1, value2, "workTerminal");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeIsNull() {
			addCriterion("suitcase_time is null");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeIsNotNull() {
			addCriterion("suitcase_time is not null");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeEqualTo(String value) {
			addCriterion("suitcase_time =", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeNotEqualTo(String value) {
			addCriterion("suitcase_time <>", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeGreaterThan(String value) {
			addCriterion("suitcase_time >", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeGreaterThanOrEqualTo(String value) {
			addCriterion("suitcase_time >=", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeLessThan(String value) {
			addCriterion("suitcase_time <", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeLessThanOrEqualTo(String value) {
			addCriterion("suitcase_time <=", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeLike(String value) {
			addCriterion("suitcase_time like", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeNotLike(String value) {
			addCriterion("suitcase_time not like", value, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeIn(List<String> values) {
			addCriterion("suitcase_time in", values, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeNotIn(List<String> values) {
			addCriterion("suitcase_time not in", values, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeBetween(String value1, String value2) {
			addCriterion("suitcase_time between", value1, value2, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseTimeNotBetween(String value1, String value2) {
			addCriterion("suitcase_time not between", value1, value2, "suitcaseTime");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteIsNull() {
			addCriterion("suitcase_site is null");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteIsNotNull() {
			addCriterion("suitcase_site is not null");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteEqualTo(String value) {
			addCriterion("suitcase_site =", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteNotEqualTo(String value) {
			addCriterion("suitcase_site <>", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteGreaterThan(String value) {
			addCriterion("suitcase_site >", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteGreaterThanOrEqualTo(String value) {
			addCriterion("suitcase_site >=", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteLessThan(String value) {
			addCriterion("suitcase_site <", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteLessThanOrEqualTo(String value) {
			addCriterion("suitcase_site <=", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteLike(String value) {
			addCriterion("suitcase_site like", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteNotLike(String value) {
			addCriterion("suitcase_site not like", value, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteIn(List<String> values) {
			addCriterion("suitcase_site in", values, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteNotIn(List<String> values) {
			addCriterion("suitcase_site not in", values, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteBetween(String value1, String value2) {
			addCriterion("suitcase_site between", value1, value2, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andSuitcaseSiteNotBetween(String value1, String value2) {
			addCriterion("suitcase_site not between", value1, value2, "suitcaseSite");
			return (Criteria) this;
		}

		public Criteria andVgmWeightIsNull() {
			addCriterion("vgm_weight is null");
			return (Criteria) this;
		}

		public Criteria andVgmWeightIsNotNull() {
			addCriterion("vgm_weight is not null");
			return (Criteria) this;
		}

		public Criteria andVgmWeightEqualTo(String value) {
			addCriterion("vgm_weight =", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightNotEqualTo(String value) {
			addCriterion("vgm_weight <>", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightGreaterThan(String value) {
			addCriterion("vgm_weight >", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightGreaterThanOrEqualTo(String value) {
			addCriterion("vgm_weight >=", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightLessThan(String value) {
			addCriterion("vgm_weight <", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightLessThanOrEqualTo(String value) {
			addCriterion("vgm_weight <=", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightLike(String value) {
			addCriterion("vgm_weight like", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightNotLike(String value) {
			addCriterion("vgm_weight not like", value, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightIn(List<String> values) {
			addCriterion("vgm_weight in", values, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightNotIn(List<String> values) {
			addCriterion("vgm_weight not in", values, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightBetween(String value1, String value2) {
			addCriterion("vgm_weight between", value1, value2, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmWeightNotBetween(String value1, String value2) {
			addCriterion("vgm_weight not between", value1, value2, "vgmWeight");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeIsNull() {
			addCriterion("vgm_result_code is null");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeIsNotNull() {
			addCriterion("vgm_result_code is not null");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeEqualTo(String value) {
			addCriterion("vgm_result_code =", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeNotEqualTo(String value) {
			addCriterion("vgm_result_code <>", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeGreaterThan(String value) {
			addCriterion("vgm_result_code >", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeGreaterThanOrEqualTo(String value) {
			addCriterion("vgm_result_code >=", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeLessThan(String value) {
			addCriterion("vgm_result_code <", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeLessThanOrEqualTo(String value) {
			addCriterion("vgm_result_code <=", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeLike(String value) {
			addCriterion("vgm_result_code like", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeNotLike(String value) {
			addCriterion("vgm_result_code not like", value, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeIn(List<String> values) {
			addCriterion("vgm_result_code in", values, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeNotIn(List<String> values) {
			addCriterion("vgm_result_code not in", values, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeBetween(String value1, String value2) {
			addCriterion("vgm_result_code between", value1, value2, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmResultCodeNotBetween(String value1, String value2) {
			addCriterion("vgm_result_code not between", value1, value2, "vgmResultCode");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescIsNull() {
			addCriterion("vgm_reuslt_desc is null");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescIsNotNull() {
			addCriterion("vgm_reuslt_desc is not null");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescEqualTo(String value) {
			addCriterion("vgm_reuslt_desc =", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescNotEqualTo(String value) {
			addCriterion("vgm_reuslt_desc <>", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescGreaterThan(String value) {
			addCriterion("vgm_reuslt_desc >", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescGreaterThanOrEqualTo(String value) {
			addCriterion("vgm_reuslt_desc >=", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescLessThan(String value) {
			addCriterion("vgm_reuslt_desc <", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescLessThanOrEqualTo(String value) {
			addCriterion("vgm_reuslt_desc <=", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescLike(String value) {
			addCriterion("vgm_reuslt_desc like", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescNotLike(String value) {
			addCriterion("vgm_reuslt_desc not like", value, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescIn(List<String> values) {
			addCriterion("vgm_reuslt_desc in", values, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescNotIn(List<String> values) {
			addCriterion("vgm_reuslt_desc not in", values, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescBetween(String value1, String value2) {
			addCriterion("vgm_reuslt_desc between", value1, value2, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVgmReusltDescNotBetween(String value1, String value2) {
			addCriterion("vgm_reuslt_desc not between", value1, value2, "vgmReusltDesc");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdIsNull() {
			addCriterion("vessel_info_id is null");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdIsNotNull() {
			addCriterion("vessel_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdEqualTo(String value) {
			addCriterion("vessel_info_id =", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdNotEqualTo(String value) {
			addCriterion("vessel_info_id <>", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdGreaterThan(String value) {
			addCriterion("vessel_info_id >", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdGreaterThanOrEqualTo(String value) {
			addCriterion("vessel_info_id >=", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdLessThan(String value) {
			addCriterion("vessel_info_id <", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdLessThanOrEqualTo(String value) {
			addCriterion("vessel_info_id <=", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdLike(String value) {
			addCriterion("vessel_info_id like", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdNotLike(String value) {
			addCriterion("vessel_info_id not like", value, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdIn(List<String> values) {
			addCriterion("vessel_info_id in", values, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdNotIn(List<String> values) {
			addCriterion("vessel_info_id not in", values, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdBetween(String value1, String value2) {
			addCriterion("vessel_info_id between", value1, value2, "vesselInfoId");
			return (Criteria) this;
		}

		public Criteria andVesselInfoIdNotBetween(String value1, String value2) {
			addCriterion("vessel_info_id not between", value1, value2, "vesselInfoId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctn_info
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctn_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 21 14:01:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}