package com.wjelogistics.edi.esb.model.entity;

public class CtnStatus {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.feed_back_desc
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String feedBackDesc;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.feed_back_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String feedBackTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.feed_back_flag1
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String feedBackFlag1;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.feed_back_flag2
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String feedBackFlag2;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.feed_back_result
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String feedBackResult;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctn_status.ctn_info_id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String ctnInfoId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.id
	 * @return  the value of ctn_status.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.id
	 * @param id  the value for ctn_status.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.status
	 * @return  the value of ctn_status.status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.status
	 * @param status  the value for ctn_status.status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.feed_back_desc
	 * @return  the value of ctn_status.feed_back_desc
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getFeedBackDesc() {
		return feedBackDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.feed_back_desc
	 * @param feedBackDesc  the value for ctn_status.feed_back_desc
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setFeedBackDesc(String feedBackDesc) {
		this.feedBackDesc = feedBackDesc;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.feed_back_time
	 * @return  the value of ctn_status.feed_back_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getFeedBackTime() {
		return feedBackTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.feed_back_time
	 * @param feedBackTime  the value for ctn_status.feed_back_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setFeedBackTime(String feedBackTime) {
		this.feedBackTime = feedBackTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.feed_back_flag1
	 * @return  the value of ctn_status.feed_back_flag1
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getFeedBackFlag1() {
		return feedBackFlag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.feed_back_flag1
	 * @param feedBackFlag1  the value for ctn_status.feed_back_flag1
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setFeedBackFlag1(String feedBackFlag1) {
		this.feedBackFlag1 = feedBackFlag1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.feed_back_flag2
	 * @return  the value of ctn_status.feed_back_flag2
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getFeedBackFlag2() {
		return feedBackFlag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.feed_back_flag2
	 * @param feedBackFlag2  the value for ctn_status.feed_back_flag2
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setFeedBackFlag2(String feedBackFlag2) {
		this.feedBackFlag2 = feedBackFlag2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.feed_back_result
	 * @return  the value of ctn_status.feed_back_result
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getFeedBackResult() {
		return feedBackResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.feed_back_result
	 * @param feedBackResult  the value for ctn_status.feed_back_result
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setFeedBackResult(String feedBackResult) {
		this.feedBackResult = feedBackResult;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctn_status.ctn_info_id
	 * @return  the value of ctn_status.ctn_info_id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getCtnInfoId() {
		return ctnInfoId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctn_status.ctn_info_id
	 * @param ctnInfoId  the value for ctn_status.ctn_info_id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setCtnInfoId(String ctnInfoId) {
		this.ctnInfoId = ctnInfoId;
	}
}