package com.wjelogistics.edi.esb.model.entity;

import java.util.ArrayList;
import java.util.List;

public class CtnStatusExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public CtnStatusExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(String value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(String value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(String value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(String value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(String value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(String value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLike(String value) {
			addCriterion("id like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotLike(String value) {
			addCriterion("id not like", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<String> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<String> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(String value1, String value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(String value1, String value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescIsNull() {
			addCriterion("feed_back_desc is null");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescIsNotNull() {
			addCriterion("feed_back_desc is not null");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescEqualTo(String value) {
			addCriterion("feed_back_desc =", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescNotEqualTo(String value) {
			addCriterion("feed_back_desc <>", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescGreaterThan(String value) {
			addCriterion("feed_back_desc >", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescGreaterThanOrEqualTo(String value) {
			addCriterion("feed_back_desc >=", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescLessThan(String value) {
			addCriterion("feed_back_desc <", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescLessThanOrEqualTo(String value) {
			addCriterion("feed_back_desc <=", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescLike(String value) {
			addCriterion("feed_back_desc like", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescNotLike(String value) {
			addCriterion("feed_back_desc not like", value, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescIn(List<String> values) {
			addCriterion("feed_back_desc in", values, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescNotIn(List<String> values) {
			addCriterion("feed_back_desc not in", values, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescBetween(String value1, String value2) {
			addCriterion("feed_back_desc between", value1, value2, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackDescNotBetween(String value1, String value2) {
			addCriterion("feed_back_desc not between", value1, value2, "feedBackDesc");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeIsNull() {
			addCriterion("feed_back_time is null");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeIsNotNull() {
			addCriterion("feed_back_time is not null");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeEqualTo(String value) {
			addCriterion("feed_back_time =", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeNotEqualTo(String value) {
			addCriterion("feed_back_time <>", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeGreaterThan(String value) {
			addCriterion("feed_back_time >", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeGreaterThanOrEqualTo(String value) {
			addCriterion("feed_back_time >=", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeLessThan(String value) {
			addCriterion("feed_back_time <", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeLessThanOrEqualTo(String value) {
			addCriterion("feed_back_time <=", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeLike(String value) {
			addCriterion("feed_back_time like", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeNotLike(String value) {
			addCriterion("feed_back_time not like", value, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeIn(List<String> values) {
			addCriterion("feed_back_time in", values, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeNotIn(List<String> values) {
			addCriterion("feed_back_time not in", values, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeBetween(String value1, String value2) {
			addCriterion("feed_back_time between", value1, value2, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackTimeNotBetween(String value1, String value2) {
			addCriterion("feed_back_time not between", value1, value2, "feedBackTime");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1IsNull() {
			addCriterion("feed_back_flag1 is null");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1IsNotNull() {
			addCriterion("feed_back_flag1 is not null");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1EqualTo(String value) {
			addCriterion("feed_back_flag1 =", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1NotEqualTo(String value) {
			addCriterion("feed_back_flag1 <>", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1GreaterThan(String value) {
			addCriterion("feed_back_flag1 >", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1GreaterThanOrEqualTo(String value) {
			addCriterion("feed_back_flag1 >=", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1LessThan(String value) {
			addCriterion("feed_back_flag1 <", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1LessThanOrEqualTo(String value) {
			addCriterion("feed_back_flag1 <=", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1Like(String value) {
			addCriterion("feed_back_flag1 like", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1NotLike(String value) {
			addCriterion("feed_back_flag1 not like", value, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1In(List<String> values) {
			addCriterion("feed_back_flag1 in", values, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1NotIn(List<String> values) {
			addCriterion("feed_back_flag1 not in", values, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1Between(String value1, String value2) {
			addCriterion("feed_back_flag1 between", value1, value2, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag1NotBetween(String value1, String value2) {
			addCriterion("feed_back_flag1 not between", value1, value2, "feedBackFlag1");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2IsNull() {
			addCriterion("feed_back_flag2 is null");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2IsNotNull() {
			addCriterion("feed_back_flag2 is not null");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2EqualTo(String value) {
			addCriterion("feed_back_flag2 =", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2NotEqualTo(String value) {
			addCriterion("feed_back_flag2 <>", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2GreaterThan(String value) {
			addCriterion("feed_back_flag2 >", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2GreaterThanOrEqualTo(String value) {
			addCriterion("feed_back_flag2 >=", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2LessThan(String value) {
			addCriterion("feed_back_flag2 <", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2LessThanOrEqualTo(String value) {
			addCriterion("feed_back_flag2 <=", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2Like(String value) {
			addCriterion("feed_back_flag2 like", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2NotLike(String value) {
			addCriterion("feed_back_flag2 not like", value, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2In(List<String> values) {
			addCriterion("feed_back_flag2 in", values, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2NotIn(List<String> values) {
			addCriterion("feed_back_flag2 not in", values, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2Between(String value1, String value2) {
			addCriterion("feed_back_flag2 between", value1, value2, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackFlag2NotBetween(String value1, String value2) {
			addCriterion("feed_back_flag2 not between", value1, value2, "feedBackFlag2");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultIsNull() {
			addCriterion("feed_back_result is null");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultIsNotNull() {
			addCriterion("feed_back_result is not null");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultEqualTo(String value) {
			addCriterion("feed_back_result =", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultNotEqualTo(String value) {
			addCriterion("feed_back_result <>", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultGreaterThan(String value) {
			addCriterion("feed_back_result >", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultGreaterThanOrEqualTo(String value) {
			addCriterion("feed_back_result >=", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultLessThan(String value) {
			addCriterion("feed_back_result <", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultLessThanOrEqualTo(String value) {
			addCriterion("feed_back_result <=", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultLike(String value) {
			addCriterion("feed_back_result like", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultNotLike(String value) {
			addCriterion("feed_back_result not like", value, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultIn(List<String> values) {
			addCriterion("feed_back_result in", values, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultNotIn(List<String> values) {
			addCriterion("feed_back_result not in", values, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultBetween(String value1, String value2) {
			addCriterion("feed_back_result between", value1, value2, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andFeedBackResultNotBetween(String value1, String value2) {
			addCriterion("feed_back_result not between", value1, value2, "feedBackResult");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdIsNull() {
			addCriterion("ctn_info_id is null");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdIsNotNull() {
			addCriterion("ctn_info_id is not null");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdEqualTo(String value) {
			addCriterion("ctn_info_id =", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdNotEqualTo(String value) {
			addCriterion("ctn_info_id <>", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdGreaterThan(String value) {
			addCriterion("ctn_info_id >", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdGreaterThanOrEqualTo(String value) {
			addCriterion("ctn_info_id >=", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdLessThan(String value) {
			addCriterion("ctn_info_id <", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdLessThanOrEqualTo(String value) {
			addCriterion("ctn_info_id <=", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdLike(String value) {
			addCriterion("ctn_info_id like", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdNotLike(String value) {
			addCriterion("ctn_info_id not like", value, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdIn(List<String> values) {
			addCriterion("ctn_info_id in", values, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdNotIn(List<String> values) {
			addCriterion("ctn_info_id not in", values, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdBetween(String value1, String value2) {
			addCriterion("ctn_info_id between", value1, value2, "ctnInfoId");
			return (Criteria) this;
		}

		public Criteria andCtnInfoIdNotBetween(String value1, String value2) {
			addCriterion("ctn_info_id not between", value1, value2, "ctnInfoId");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctn_status
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctn_status
     *
     * @mbg.generated do_not_delete_during_merge Tue Mar 21 14:01:10 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}