package com.wjelogistics.edi.esb.model.entity;

public class CtnStatus {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.result
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String result;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.flag1
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String flag1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.flag2
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String flag2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ctn_status.ctn_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    private String ctnInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.id
     *
     * @return the value of ctn_status.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.id
     *
     * @param id the value for ctn_status.id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.status
     *
     * @return the value of ctn_status.status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.status
     *
     * @param status the value for ctn_status.status
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.result
     *
     * @return the value of ctn_status.result
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getResult() {
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.result
     *
     * @param result the value for ctn_status.result
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setResult(String result) {
        this.result = result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.time
     *
     * @return the value of ctn_status.time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.time
     *
     * @param time the value for ctn_status.time
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setTime(String time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.flag1
     *
     * @return the value of ctn_status.flag1
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getFlag1() {
        return flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.flag1
     *
     * @param flag1 the value for ctn_status.flag1
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setFlag1(String flag1) {
        this.flag1 = flag1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.flag2
     *
     * @return the value of ctn_status.flag2
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getFlag2() {
        return flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.flag2
     *
     * @param flag2 the value for ctn_status.flag2
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setFlag2(String flag2) {
        this.flag2 = flag2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.desc
     *
     * @return the value of ctn_status.desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.desc
     *
     * @param desc the value for ctn_status.desc
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ctn_status.ctn_info_id
     *
     * @return the value of ctn_status.ctn_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public String getCtnInfoId() {
        return ctnInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ctn_status.ctn_info_id
     *
     * @param ctnInfoId the value for ctn_status.ctn_info_id
     *
     * @mbg.generated Tue Mar 21 14:01:10 CST 2017
     */
    public void setCtnInfoId(String ctnInfoId) {
        this.ctnInfoId = ctnInfoId;
    }
}