package com.wjelogistics.edi.esb.model.entity;

public class DatResult {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.id
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.agent
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String agent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.angentcode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String angentcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.billno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String billno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.compare_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String compareFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.compare_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String compareTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.containerno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String containerno;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.custom_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String customFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.custom_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String customRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.envessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String envessel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.ifcsum_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String ifcsumFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.linecode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String linecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.matou
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String matou;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.matou_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String matouFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.matou_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String matouRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.pass_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String passFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.reason
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.receivetime
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String receivetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.send_enable
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sendEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.send_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sendFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.send_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.sizetype
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sizetype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.sld_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sldFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.sld_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String sldRemark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.unvessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String unvessel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dat_result.voyage
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    private String voyage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.id
     *
     * @return the value of dat_result.id
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.id
     *
     * @param id the value for dat_result.id
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.agent
     *
     * @return the value of dat_result.agent
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getAgent() {
        return agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.agent
     *
     * @param agent the value for dat_result.agent
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setAgent(String agent) {
        this.agent = agent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.angentcode
     *
     * @return the value of dat_result.angentcode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getAngentcode() {
        return angentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.angentcode
     *
     * @param angentcode the value for dat_result.angentcode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setAngentcode(String angentcode) {
        this.angentcode = angentcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.billno
     *
     * @return the value of dat_result.billno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getBillno() {
        return billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.billno
     *
     * @param billno the value for dat_result.billno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setBillno(String billno) {
        this.billno = billno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.compare_flag
     *
     * @return the value of dat_result.compare_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getCompareFlag() {
        return compareFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.compare_flag
     *
     * @param compareFlag the value for dat_result.compare_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setCompareFlag(String compareFlag) {
        this.compareFlag = compareFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.compare_time
     *
     * @return the value of dat_result.compare_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getCompareTime() {
        return compareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.compare_time
     *
     * @param compareTime the value for dat_result.compare_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setCompareTime(String compareTime) {
        this.compareTime = compareTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.containerno
     *
     * @return the value of dat_result.containerno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getContainerno() {
        return containerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.containerno
     *
     * @param containerno the value for dat_result.containerno
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setContainerno(String containerno) {
        this.containerno = containerno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.custom_flag
     *
     * @return the value of dat_result.custom_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getCustomFlag() {
        return customFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.custom_flag
     *
     * @param customFlag the value for dat_result.custom_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setCustomFlag(String customFlag) {
        this.customFlag = customFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.custom_remark
     *
     * @return the value of dat_result.custom_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getCustomRemark() {
        return customRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.custom_remark
     *
     * @param customRemark the value for dat_result.custom_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setCustomRemark(String customRemark) {
        this.customRemark = customRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.envessel
     *
     * @return the value of dat_result.envessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getEnvessel() {
        return envessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.envessel
     *
     * @param envessel the value for dat_result.envessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setEnvessel(String envessel) {
        this.envessel = envessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.ifcsum_flag
     *
     * @return the value of dat_result.ifcsum_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getIfcsumFlag() {
        return ifcsumFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.ifcsum_flag
     *
     * @param ifcsumFlag the value for dat_result.ifcsum_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setIfcsumFlag(String ifcsumFlag) {
        this.ifcsumFlag = ifcsumFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.linecode
     *
     * @return the value of dat_result.linecode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getLinecode() {
        return linecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.linecode
     *
     * @param linecode the value for dat_result.linecode
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setLinecode(String linecode) {
        this.linecode = linecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.matou
     *
     * @return the value of dat_result.matou
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getMatou() {
        return matou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.matou
     *
     * @param matou the value for dat_result.matou
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setMatou(String matou) {
        this.matou = matou;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.matou_flag
     *
     * @return the value of dat_result.matou_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getMatouFlag() {
        return matouFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.matou_flag
     *
     * @param matouFlag the value for dat_result.matou_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setMatouFlag(String matouFlag) {
        this.matouFlag = matouFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.matou_remark
     *
     * @return the value of dat_result.matou_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getMatouRemark() {
        return matouRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.matou_remark
     *
     * @param matouRemark the value for dat_result.matou_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setMatouRemark(String matouRemark) {
        this.matouRemark = matouRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.pass_flag
     *
     * @return the value of dat_result.pass_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getPassFlag() {
        return passFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.pass_flag
     *
     * @param passFlag the value for dat_result.pass_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setPassFlag(String passFlag) {
        this.passFlag = passFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.reason
     *
     * @return the value of dat_result.reason
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.reason
     *
     * @param reason the value for dat_result.reason
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.receivetime
     *
     * @return the value of dat_result.receivetime
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getReceivetime() {
        return receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.receivetime
     *
     * @param receivetime the value for dat_result.receivetime
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setReceivetime(String receivetime) {
        this.receivetime = receivetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.remark
     *
     * @return the value of dat_result.remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.remark
     *
     * @param remark the value for dat_result.remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.send_enable
     *
     * @return the value of dat_result.send_enable
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSendEnable() {
        return sendEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.send_enable
     *
     * @param sendEnable the value for dat_result.send_enable
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSendEnable(String sendEnable) {
        this.sendEnable = sendEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.send_flag
     *
     * @return the value of dat_result.send_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSendFlag() {
        return sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.send_flag
     *
     * @param sendFlag the value for dat_result.send_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSendFlag(String sendFlag) {
        this.sendFlag = sendFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.send_time
     *
     * @return the value of dat_result.send_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.send_time
     *
     * @param sendTime the value for dat_result.send_time
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSendTime(String sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.sizetype
     *
     * @return the value of dat_result.sizetype
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSizetype() {
        return sizetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.sizetype
     *
     * @param sizetype the value for dat_result.sizetype
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSizetype(String sizetype) {
        this.sizetype = sizetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.sld_flag
     *
     * @return the value of dat_result.sld_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSldFlag() {
        return sldFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.sld_flag
     *
     * @param sldFlag the value for dat_result.sld_flag
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSldFlag(String sldFlag) {
        this.sldFlag = sldFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.sld_remark
     *
     * @return the value of dat_result.sld_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getSldRemark() {
        return sldRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.sld_remark
     *
     * @param sldRemark the value for dat_result.sld_remark
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setSldRemark(String sldRemark) {
        this.sldRemark = sldRemark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.unvessel
     *
     * @return the value of dat_result.unvessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getUnvessel() {
        return unvessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.unvessel
     *
     * @param unvessel the value for dat_result.unvessel
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setUnvessel(String unvessel) {
        this.unvessel = unvessel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dat_result.voyage
     *
     * @return the value of dat_result.voyage
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getVoyage() {
        return voyage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dat_result.voyage
     *
     * @param voyage the value for dat_result.voyage
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setVoyage(String voyage) {
        this.voyage = voyage;
    }
}