package com.wjelogistics.edi.esb.model.entity;

import java.util.ArrayList;
import java.util.List;

public class DatResultExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public DatResultExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAgentIsNull() {
            addCriterion("agent is null");
            return (Criteria) this;
        }

        public Criteria andAgentIsNotNull() {
            addCriterion("agent is not null");
            return (Criteria) this;
        }

        public Criteria andAgentEqualTo(String value) {
            addCriterion("agent =", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotEqualTo(String value) {
            addCriterion("agent <>", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThan(String value) {
            addCriterion("agent >", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentGreaterThanOrEqualTo(String value) {
            addCriterion("agent >=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThan(String value) {
            addCriterion("agent <", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLessThanOrEqualTo(String value) {
            addCriterion("agent <=", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentLike(String value) {
            addCriterion("agent like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotLike(String value) {
            addCriterion("agent not like", value, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentIn(List<String> values) {
            addCriterion("agent in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotIn(List<String> values) {
            addCriterion("agent not in", values, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentBetween(String value1, String value2) {
            addCriterion("agent between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAgentNotBetween(String value1, String value2) {
            addCriterion("agent not between", value1, value2, "agent");
            return (Criteria) this;
        }

        public Criteria andAngentcodeIsNull() {
            addCriterion("angentcode is null");
            return (Criteria) this;
        }

        public Criteria andAngentcodeIsNotNull() {
            addCriterion("angentcode is not null");
            return (Criteria) this;
        }

        public Criteria andAngentcodeEqualTo(String value) {
            addCriterion("angentcode =", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeNotEqualTo(String value) {
            addCriterion("angentcode <>", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeGreaterThan(String value) {
            addCriterion("angentcode >", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeGreaterThanOrEqualTo(String value) {
            addCriterion("angentcode >=", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeLessThan(String value) {
            addCriterion("angentcode <", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeLessThanOrEqualTo(String value) {
            addCriterion("angentcode <=", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeLike(String value) {
            addCriterion("angentcode like", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeNotLike(String value) {
            addCriterion("angentcode not like", value, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeIn(List<String> values) {
            addCriterion("angentcode in", values, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeNotIn(List<String> values) {
            addCriterion("angentcode not in", values, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeBetween(String value1, String value2) {
            addCriterion("angentcode between", value1, value2, "angentcode");
            return (Criteria) this;
        }

        public Criteria andAngentcodeNotBetween(String value1, String value2) {
            addCriterion("angentcode not between", value1, value2, "angentcode");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNull() {
            addCriterion("billno is null");
            return (Criteria) this;
        }

        public Criteria andBillnoIsNotNull() {
            addCriterion("billno is not null");
            return (Criteria) this;
        }

        public Criteria andBillnoEqualTo(String value) {
            addCriterion("billno =", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotEqualTo(String value) {
            addCriterion("billno <>", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThan(String value) {
            addCriterion("billno >", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoGreaterThanOrEqualTo(String value) {
            addCriterion("billno >=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThan(String value) {
            addCriterion("billno <", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLessThanOrEqualTo(String value) {
            addCriterion("billno <=", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoLike(String value) {
            addCriterion("billno like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotLike(String value) {
            addCriterion("billno not like", value, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoIn(List<String> values) {
            addCriterion("billno in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotIn(List<String> values) {
            addCriterion("billno not in", values, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoBetween(String value1, String value2) {
            addCriterion("billno between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andBillnoNotBetween(String value1, String value2) {
            addCriterion("billno not between", value1, value2, "billno");
            return (Criteria) this;
        }

        public Criteria andCompareFlagIsNull() {
            addCriterion("compare_flag is null");
            return (Criteria) this;
        }

        public Criteria andCompareFlagIsNotNull() {
            addCriterion("compare_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCompareFlagEqualTo(String value) {
            addCriterion("compare_flag =", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagNotEqualTo(String value) {
            addCriterion("compare_flag <>", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagGreaterThan(String value) {
            addCriterion("compare_flag >", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagGreaterThanOrEqualTo(String value) {
            addCriterion("compare_flag >=", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagLessThan(String value) {
            addCriterion("compare_flag <", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagLessThanOrEqualTo(String value) {
            addCriterion("compare_flag <=", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagLike(String value) {
            addCriterion("compare_flag like", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagNotLike(String value) {
            addCriterion("compare_flag not like", value, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagIn(List<String> values) {
            addCriterion("compare_flag in", values, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagNotIn(List<String> values) {
            addCriterion("compare_flag not in", values, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagBetween(String value1, String value2) {
            addCriterion("compare_flag between", value1, value2, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareFlagNotBetween(String value1, String value2) {
            addCriterion("compare_flag not between", value1, value2, "compareFlag");
            return (Criteria) this;
        }

        public Criteria andCompareTimeIsNull() {
            addCriterion("compare_time is null");
            return (Criteria) this;
        }

        public Criteria andCompareTimeIsNotNull() {
            addCriterion("compare_time is not null");
            return (Criteria) this;
        }

        public Criteria andCompareTimeEqualTo(String value) {
            addCriterion("compare_time =", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeNotEqualTo(String value) {
            addCriterion("compare_time <>", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeGreaterThan(String value) {
            addCriterion("compare_time >", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeGreaterThanOrEqualTo(String value) {
            addCriterion("compare_time >=", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeLessThan(String value) {
            addCriterion("compare_time <", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeLessThanOrEqualTo(String value) {
            addCriterion("compare_time <=", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeLike(String value) {
            addCriterion("compare_time like", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeNotLike(String value) {
            addCriterion("compare_time not like", value, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeIn(List<String> values) {
            addCriterion("compare_time in", values, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeNotIn(List<String> values) {
            addCriterion("compare_time not in", values, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeBetween(String value1, String value2) {
            addCriterion("compare_time between", value1, value2, "compareTime");
            return (Criteria) this;
        }

        public Criteria andCompareTimeNotBetween(String value1, String value2) {
            addCriterion("compare_time not between", value1, value2, "compareTime");
            return (Criteria) this;
        }

        public Criteria andContainernoIsNull() {
            addCriterion("containerno is null");
            return (Criteria) this;
        }

        public Criteria andContainernoIsNotNull() {
            addCriterion("containerno is not null");
            return (Criteria) this;
        }

        public Criteria andContainernoEqualTo(String value) {
            addCriterion("containerno =", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoNotEqualTo(String value) {
            addCriterion("containerno <>", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoGreaterThan(String value) {
            addCriterion("containerno >", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoGreaterThanOrEqualTo(String value) {
            addCriterion("containerno >=", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoLessThan(String value) {
            addCriterion("containerno <", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoLessThanOrEqualTo(String value) {
            addCriterion("containerno <=", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoLike(String value) {
            addCriterion("containerno like", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoNotLike(String value) {
            addCriterion("containerno not like", value, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoIn(List<String> values) {
            addCriterion("containerno in", values, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoNotIn(List<String> values) {
            addCriterion("containerno not in", values, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoBetween(String value1, String value2) {
            addCriterion("containerno between", value1, value2, "containerno");
            return (Criteria) this;
        }

        public Criteria andContainernoNotBetween(String value1, String value2) {
            addCriterion("containerno not between", value1, value2, "containerno");
            return (Criteria) this;
        }

        public Criteria andCustomFlagIsNull() {
            addCriterion("custom_flag is null");
            return (Criteria) this;
        }

        public Criteria andCustomFlagIsNotNull() {
            addCriterion("custom_flag is not null");
            return (Criteria) this;
        }

        public Criteria andCustomFlagEqualTo(String value) {
            addCriterion("custom_flag =", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagNotEqualTo(String value) {
            addCriterion("custom_flag <>", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagGreaterThan(String value) {
            addCriterion("custom_flag >", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagGreaterThanOrEqualTo(String value) {
            addCriterion("custom_flag >=", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagLessThan(String value) {
            addCriterion("custom_flag <", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagLessThanOrEqualTo(String value) {
            addCriterion("custom_flag <=", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagLike(String value) {
            addCriterion("custom_flag like", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagNotLike(String value) {
            addCriterion("custom_flag not like", value, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagIn(List<String> values) {
            addCriterion("custom_flag in", values, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagNotIn(List<String> values) {
            addCriterion("custom_flag not in", values, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagBetween(String value1, String value2) {
            addCriterion("custom_flag between", value1, value2, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomFlagNotBetween(String value1, String value2) {
            addCriterion("custom_flag not between", value1, value2, "customFlag");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkIsNull() {
            addCriterion("custom_remark is null");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkIsNotNull() {
            addCriterion("custom_remark is not null");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkEqualTo(String value) {
            addCriterion("custom_remark =", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkNotEqualTo(String value) {
            addCriterion("custom_remark <>", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkGreaterThan(String value) {
            addCriterion("custom_remark >", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("custom_remark >=", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkLessThan(String value) {
            addCriterion("custom_remark <", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkLessThanOrEqualTo(String value) {
            addCriterion("custom_remark <=", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkLike(String value) {
            addCriterion("custom_remark like", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkNotLike(String value) {
            addCriterion("custom_remark not like", value, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkIn(List<String> values) {
            addCriterion("custom_remark in", values, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkNotIn(List<String> values) {
            addCriterion("custom_remark not in", values, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkBetween(String value1, String value2) {
            addCriterion("custom_remark between", value1, value2, "customRemark");
            return (Criteria) this;
        }

        public Criteria andCustomRemarkNotBetween(String value1, String value2) {
            addCriterion("custom_remark not between", value1, value2, "customRemark");
            return (Criteria) this;
        }

        public Criteria andEnvesselIsNull() {
            addCriterion("envessel is null");
            return (Criteria) this;
        }

        public Criteria andEnvesselIsNotNull() {
            addCriterion("envessel is not null");
            return (Criteria) this;
        }

        public Criteria andEnvesselEqualTo(String value) {
            addCriterion("envessel =", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselNotEqualTo(String value) {
            addCriterion("envessel <>", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselGreaterThan(String value) {
            addCriterion("envessel >", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselGreaterThanOrEqualTo(String value) {
            addCriterion("envessel >=", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselLessThan(String value) {
            addCriterion("envessel <", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselLessThanOrEqualTo(String value) {
            addCriterion("envessel <=", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselLike(String value) {
            addCriterion("envessel like", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselNotLike(String value) {
            addCriterion("envessel not like", value, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselIn(List<String> values) {
            addCriterion("envessel in", values, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselNotIn(List<String> values) {
            addCriterion("envessel not in", values, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselBetween(String value1, String value2) {
            addCriterion("envessel between", value1, value2, "envessel");
            return (Criteria) this;
        }

        public Criteria andEnvesselNotBetween(String value1, String value2) {
            addCriterion("envessel not between", value1, value2, "envessel");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagIsNull() {
            addCriterion("ifcsum_flag is null");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagIsNotNull() {
            addCriterion("ifcsum_flag is not null");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagEqualTo(String value) {
            addCriterion("ifcsum_flag =", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagNotEqualTo(String value) {
            addCriterion("ifcsum_flag <>", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagGreaterThan(String value) {
            addCriterion("ifcsum_flag >", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagGreaterThanOrEqualTo(String value) {
            addCriterion("ifcsum_flag >=", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagLessThan(String value) {
            addCriterion("ifcsum_flag <", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagLessThanOrEqualTo(String value) {
            addCriterion("ifcsum_flag <=", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagLike(String value) {
            addCriterion("ifcsum_flag like", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagNotLike(String value) {
            addCriterion("ifcsum_flag not like", value, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagIn(List<String> values) {
            addCriterion("ifcsum_flag in", values, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagNotIn(List<String> values) {
            addCriterion("ifcsum_flag not in", values, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagBetween(String value1, String value2) {
            addCriterion("ifcsum_flag between", value1, value2, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andIfcsumFlagNotBetween(String value1, String value2) {
            addCriterion("ifcsum_flag not between", value1, value2, "ifcsumFlag");
            return (Criteria) this;
        }

        public Criteria andLinecodeIsNull() {
            addCriterion("linecode is null");
            return (Criteria) this;
        }

        public Criteria andLinecodeIsNotNull() {
            addCriterion("linecode is not null");
            return (Criteria) this;
        }

        public Criteria andLinecodeEqualTo(String value) {
            addCriterion("linecode =", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeNotEqualTo(String value) {
            addCriterion("linecode <>", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeGreaterThan(String value) {
            addCriterion("linecode >", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeGreaterThanOrEqualTo(String value) {
            addCriterion("linecode >=", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeLessThan(String value) {
            addCriterion("linecode <", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeLessThanOrEqualTo(String value) {
            addCriterion("linecode <=", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeLike(String value) {
            addCriterion("linecode like", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeNotLike(String value) {
            addCriterion("linecode not like", value, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeIn(List<String> values) {
            addCriterion("linecode in", values, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeNotIn(List<String> values) {
            addCriterion("linecode not in", values, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeBetween(String value1, String value2) {
            addCriterion("linecode between", value1, value2, "linecode");
            return (Criteria) this;
        }

        public Criteria andLinecodeNotBetween(String value1, String value2) {
            addCriterion("linecode not between", value1, value2, "linecode");
            return (Criteria) this;
        }

        public Criteria andMatouIsNull() {
            addCriterion("matou is null");
            return (Criteria) this;
        }

        public Criteria andMatouIsNotNull() {
            addCriterion("matou is not null");
            return (Criteria) this;
        }

        public Criteria andMatouEqualTo(String value) {
            addCriterion("matou =", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouNotEqualTo(String value) {
            addCriterion("matou <>", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouGreaterThan(String value) {
            addCriterion("matou >", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouGreaterThanOrEqualTo(String value) {
            addCriterion("matou >=", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouLessThan(String value) {
            addCriterion("matou <", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouLessThanOrEqualTo(String value) {
            addCriterion("matou <=", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouLike(String value) {
            addCriterion("matou like", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouNotLike(String value) {
            addCriterion("matou not like", value, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouIn(List<String> values) {
            addCriterion("matou in", values, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouNotIn(List<String> values) {
            addCriterion("matou not in", values, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouBetween(String value1, String value2) {
            addCriterion("matou between", value1, value2, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouNotBetween(String value1, String value2) {
            addCriterion("matou not between", value1, value2, "matou");
            return (Criteria) this;
        }

        public Criteria andMatouFlagIsNull() {
            addCriterion("matou_flag is null");
            return (Criteria) this;
        }

        public Criteria andMatouFlagIsNotNull() {
            addCriterion("matou_flag is not null");
            return (Criteria) this;
        }

        public Criteria andMatouFlagEqualTo(String value) {
            addCriterion("matou_flag =", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagNotEqualTo(String value) {
            addCriterion("matou_flag <>", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagGreaterThan(String value) {
            addCriterion("matou_flag >", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagGreaterThanOrEqualTo(String value) {
            addCriterion("matou_flag >=", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagLessThan(String value) {
            addCriterion("matou_flag <", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagLessThanOrEqualTo(String value) {
            addCriterion("matou_flag <=", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagLike(String value) {
            addCriterion("matou_flag like", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagNotLike(String value) {
            addCriterion("matou_flag not like", value, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagIn(List<String> values) {
            addCriterion("matou_flag in", values, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagNotIn(List<String> values) {
            addCriterion("matou_flag not in", values, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagBetween(String value1, String value2) {
            addCriterion("matou_flag between", value1, value2, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouFlagNotBetween(String value1, String value2) {
            addCriterion("matou_flag not between", value1, value2, "matouFlag");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkIsNull() {
            addCriterion("matou_remark is null");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkIsNotNull() {
            addCriterion("matou_remark is not null");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkEqualTo(String value) {
            addCriterion("matou_remark =", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkNotEqualTo(String value) {
            addCriterion("matou_remark <>", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkGreaterThan(String value) {
            addCriterion("matou_remark >", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("matou_remark >=", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkLessThan(String value) {
            addCriterion("matou_remark <", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkLessThanOrEqualTo(String value) {
            addCriterion("matou_remark <=", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkLike(String value) {
            addCriterion("matou_remark like", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkNotLike(String value) {
            addCriterion("matou_remark not like", value, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkIn(List<String> values) {
            addCriterion("matou_remark in", values, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkNotIn(List<String> values) {
            addCriterion("matou_remark not in", values, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkBetween(String value1, String value2) {
            addCriterion("matou_remark between", value1, value2, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andMatouRemarkNotBetween(String value1, String value2) {
            addCriterion("matou_remark not between", value1, value2, "matouRemark");
            return (Criteria) this;
        }

        public Criteria andPassFlagIsNull() {
            addCriterion("pass_flag is null");
            return (Criteria) this;
        }

        public Criteria andPassFlagIsNotNull() {
            addCriterion("pass_flag is not null");
            return (Criteria) this;
        }

        public Criteria andPassFlagEqualTo(String value) {
            addCriterion("pass_flag =", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagNotEqualTo(String value) {
            addCriterion("pass_flag <>", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagGreaterThan(String value) {
            addCriterion("pass_flag >", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagGreaterThanOrEqualTo(String value) {
            addCriterion("pass_flag >=", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagLessThan(String value) {
            addCriterion("pass_flag <", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagLessThanOrEqualTo(String value) {
            addCriterion("pass_flag <=", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagLike(String value) {
            addCriterion("pass_flag like", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagNotLike(String value) {
            addCriterion("pass_flag not like", value, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagIn(List<String> values) {
            addCriterion("pass_flag in", values, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagNotIn(List<String> values) {
            addCriterion("pass_flag not in", values, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagBetween(String value1, String value2) {
            addCriterion("pass_flag between", value1, value2, "passFlag");
            return (Criteria) this;
        }

        public Criteria andPassFlagNotBetween(String value1, String value2) {
            addCriterion("pass_flag not between", value1, value2, "passFlag");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNull() {
            addCriterion("receivetime is null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIsNotNull() {
            addCriterion("receivetime is not null");
            return (Criteria) this;
        }

        public Criteria andReceivetimeEqualTo(String value) {
            addCriterion("receivetime =", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotEqualTo(String value) {
            addCriterion("receivetime <>", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThan(String value) {
            addCriterion("receivetime >", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeGreaterThanOrEqualTo(String value) {
            addCriterion("receivetime >=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThan(String value) {
            addCriterion("receivetime <", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLessThanOrEqualTo(String value) {
            addCriterion("receivetime <=", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeLike(String value) {
            addCriterion("receivetime like", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotLike(String value) {
            addCriterion("receivetime not like", value, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeIn(List<String> values) {
            addCriterion("receivetime in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotIn(List<String> values) {
            addCriterion("receivetime not in", values, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeBetween(String value1, String value2) {
            addCriterion("receivetime between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andReceivetimeNotBetween(String value1, String value2) {
            addCriterion("receivetime not between", value1, value2, "receivetime");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andSendEnableIsNull() {
            addCriterion("send_enable is null");
            return (Criteria) this;
        }

        public Criteria andSendEnableIsNotNull() {
            addCriterion("send_enable is not null");
            return (Criteria) this;
        }

        public Criteria andSendEnableEqualTo(String value) {
            addCriterion("send_enable =", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableNotEqualTo(String value) {
            addCriterion("send_enable <>", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableGreaterThan(String value) {
            addCriterion("send_enable >", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableGreaterThanOrEqualTo(String value) {
            addCriterion("send_enable >=", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableLessThan(String value) {
            addCriterion("send_enable <", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableLessThanOrEqualTo(String value) {
            addCriterion("send_enable <=", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableLike(String value) {
            addCriterion("send_enable like", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableNotLike(String value) {
            addCriterion("send_enable not like", value, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableIn(List<String> values) {
            addCriterion("send_enable in", values, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableNotIn(List<String> values) {
            addCriterion("send_enable not in", values, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableBetween(String value1, String value2) {
            addCriterion("send_enable between", value1, value2, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendEnableNotBetween(String value1, String value2) {
            addCriterion("send_enable not between", value1, value2, "sendEnable");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNull() {
            addCriterion("send_flag is null");
            return (Criteria) this;
        }

        public Criteria andSendFlagIsNotNull() {
            addCriterion("send_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSendFlagEqualTo(String value) {
            addCriterion("send_flag =", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotEqualTo(String value) {
            addCriterion("send_flag <>", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThan(String value) {
            addCriterion("send_flag >", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagGreaterThanOrEqualTo(String value) {
            addCriterion("send_flag >=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThan(String value) {
            addCriterion("send_flag <", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLessThanOrEqualTo(String value) {
            addCriterion("send_flag <=", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagLike(String value) {
            addCriterion("send_flag like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotLike(String value) {
            addCriterion("send_flag not like", value, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagIn(List<String> values) {
            addCriterion("send_flag in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotIn(List<String> values) {
            addCriterion("send_flag not in", values, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagBetween(String value1, String value2) {
            addCriterion("send_flag between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendFlagNotBetween(String value1, String value2) {
            addCriterion("send_flag not between", value1, value2, "sendFlag");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNull() {
            addCriterion("send_time is null");
            return (Criteria) this;
        }

        public Criteria andSendTimeIsNotNull() {
            addCriterion("send_time is not null");
            return (Criteria) this;
        }

        public Criteria andSendTimeEqualTo(String value) {
            addCriterion("send_time =", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotEqualTo(String value) {
            addCriterion("send_time <>", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThan(String value) {
            addCriterion("send_time >", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeGreaterThanOrEqualTo(String value) {
            addCriterion("send_time >=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThan(String value) {
            addCriterion("send_time <", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLessThanOrEqualTo(String value) {
            addCriterion("send_time <=", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeLike(String value) {
            addCriterion("send_time like", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotLike(String value) {
            addCriterion("send_time not like", value, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeIn(List<String> values) {
            addCriterion("send_time in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotIn(List<String> values) {
            addCriterion("send_time not in", values, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeBetween(String value1, String value2) {
            addCriterion("send_time between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSendTimeNotBetween(String value1, String value2) {
            addCriterion("send_time not between", value1, value2, "sendTime");
            return (Criteria) this;
        }

        public Criteria andSizetypeIsNull() {
            addCriterion("sizetype is null");
            return (Criteria) this;
        }

        public Criteria andSizetypeIsNotNull() {
            addCriterion("sizetype is not null");
            return (Criteria) this;
        }

        public Criteria andSizetypeEqualTo(String value) {
            addCriterion("sizetype =", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeNotEqualTo(String value) {
            addCriterion("sizetype <>", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeGreaterThan(String value) {
            addCriterion("sizetype >", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeGreaterThanOrEqualTo(String value) {
            addCriterion("sizetype >=", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeLessThan(String value) {
            addCriterion("sizetype <", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeLessThanOrEqualTo(String value) {
            addCriterion("sizetype <=", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeLike(String value) {
            addCriterion("sizetype like", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeNotLike(String value) {
            addCriterion("sizetype not like", value, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeIn(List<String> values) {
            addCriterion("sizetype in", values, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeNotIn(List<String> values) {
            addCriterion("sizetype not in", values, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeBetween(String value1, String value2) {
            addCriterion("sizetype between", value1, value2, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSizetypeNotBetween(String value1, String value2) {
            addCriterion("sizetype not between", value1, value2, "sizetype");
            return (Criteria) this;
        }

        public Criteria andSldFlagIsNull() {
            addCriterion("sld_flag is null");
            return (Criteria) this;
        }

        public Criteria andSldFlagIsNotNull() {
            addCriterion("sld_flag is not null");
            return (Criteria) this;
        }

        public Criteria andSldFlagEqualTo(String value) {
            addCriterion("sld_flag =", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagNotEqualTo(String value) {
            addCriterion("sld_flag <>", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagGreaterThan(String value) {
            addCriterion("sld_flag >", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagGreaterThanOrEqualTo(String value) {
            addCriterion("sld_flag >=", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagLessThan(String value) {
            addCriterion("sld_flag <", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagLessThanOrEqualTo(String value) {
            addCriterion("sld_flag <=", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagLike(String value) {
            addCriterion("sld_flag like", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagNotLike(String value) {
            addCriterion("sld_flag not like", value, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagIn(List<String> values) {
            addCriterion("sld_flag in", values, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagNotIn(List<String> values) {
            addCriterion("sld_flag not in", values, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagBetween(String value1, String value2) {
            addCriterion("sld_flag between", value1, value2, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldFlagNotBetween(String value1, String value2) {
            addCriterion("sld_flag not between", value1, value2, "sldFlag");
            return (Criteria) this;
        }

        public Criteria andSldRemarkIsNull() {
            addCriterion("sld_remark is null");
            return (Criteria) this;
        }

        public Criteria andSldRemarkIsNotNull() {
            addCriterion("sld_remark is not null");
            return (Criteria) this;
        }

        public Criteria andSldRemarkEqualTo(String value) {
            addCriterion("sld_remark =", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkNotEqualTo(String value) {
            addCriterion("sld_remark <>", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkGreaterThan(String value) {
            addCriterion("sld_remark >", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("sld_remark >=", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkLessThan(String value) {
            addCriterion("sld_remark <", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkLessThanOrEqualTo(String value) {
            addCriterion("sld_remark <=", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkLike(String value) {
            addCriterion("sld_remark like", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkNotLike(String value) {
            addCriterion("sld_remark not like", value, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkIn(List<String> values) {
            addCriterion("sld_remark in", values, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkNotIn(List<String> values) {
            addCriterion("sld_remark not in", values, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkBetween(String value1, String value2) {
            addCriterion("sld_remark between", value1, value2, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andSldRemarkNotBetween(String value1, String value2) {
            addCriterion("sld_remark not between", value1, value2, "sldRemark");
            return (Criteria) this;
        }

        public Criteria andUnvesselIsNull() {
            addCriterion("unvessel is null");
            return (Criteria) this;
        }

        public Criteria andUnvesselIsNotNull() {
            addCriterion("unvessel is not null");
            return (Criteria) this;
        }

        public Criteria andUnvesselEqualTo(String value) {
            addCriterion("unvessel =", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselNotEqualTo(String value) {
            addCriterion("unvessel <>", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselGreaterThan(String value) {
            addCriterion("unvessel >", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselGreaterThanOrEqualTo(String value) {
            addCriterion("unvessel >=", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselLessThan(String value) {
            addCriterion("unvessel <", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselLessThanOrEqualTo(String value) {
            addCriterion("unvessel <=", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselLike(String value) {
            addCriterion("unvessel like", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselNotLike(String value) {
            addCriterion("unvessel not like", value, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselIn(List<String> values) {
            addCriterion("unvessel in", values, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselNotIn(List<String> values) {
            addCriterion("unvessel not in", values, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselBetween(String value1, String value2) {
            addCriterion("unvessel between", value1, value2, "unvessel");
            return (Criteria) this;
        }

        public Criteria andUnvesselNotBetween(String value1, String value2) {
            addCriterion("unvessel not between", value1, value2, "unvessel");
            return (Criteria) this;
        }

        public Criteria andVoyageIsNull() {
            addCriterion("voyage is null");
            return (Criteria) this;
        }

        public Criteria andVoyageIsNotNull() {
            addCriterion("voyage is not null");
            return (Criteria) this;
        }

        public Criteria andVoyageEqualTo(String value) {
            addCriterion("voyage =", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageNotEqualTo(String value) {
            addCriterion("voyage <>", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageGreaterThan(String value) {
            addCriterion("voyage >", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageGreaterThanOrEqualTo(String value) {
            addCriterion("voyage >=", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageLessThan(String value) {
            addCriterion("voyage <", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageLessThanOrEqualTo(String value) {
            addCriterion("voyage <=", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageLike(String value) {
            addCriterion("voyage like", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageNotLike(String value) {
            addCriterion("voyage not like", value, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageIn(List<String> values) {
            addCriterion("voyage in", values, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageNotIn(List<String> values) {
            addCriterion("voyage not in", values, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageBetween(String value1, String value2) {
            addCriterion("voyage between", value1, value2, "voyage");
            return (Criteria) this;
        }

        public Criteria andVoyageNotBetween(String value1, String value2) {
            addCriterion("voyage not between", value1, value2, "voyage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dat_result
     *
     * @mbg.generated do_not_delete_during_merge Thu Apr 06 11:45:29 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table dat_result
     *
     * @mbg.generated Thu Apr 06 11:45:29 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}