package com.wjelogistics.edi.esb.model.entity;

import java.util.List;

public class VesselInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.vessel_uncode
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String vesselUncode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.vessel_ename
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String vesselEname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.direction
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String direction;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.terminal
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String terminal;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.arrival_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String arrivalTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.voyage
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String voyage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column vessel_info.sailing_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	private String sailingTime;

	private List<CtnInfo> ctn_no_list;

	public List<CtnInfo> getCtn_no_list() {
		return ctn_no_list;
	}

	public void setCtn_no_list(List<CtnInfo> ctn_no_list) {
		this.ctn_no_list = ctn_no_list;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.id
	 * @return  the value of vessel_info.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.id
	 * @param id  the value for vessel_info.id
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.vessel_uncode
	 * @return  the value of vessel_info.vessel_uncode
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getVesselUncode() {
		return vesselUncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.vessel_uncode
	 * @param vesselUncode  the value for vessel_info.vessel_uncode
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setVesselUncode(String vesselUncode) {
		this.vesselUncode = vesselUncode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.vessel_ename
	 * @return  the value of vessel_info.vessel_ename
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getVesselEname() {
		return vesselEname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.vessel_ename
	 * @param vesselEname  the value for vessel_info.vessel_ename
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setVesselEname(String vesselEname) {
		this.vesselEname = vesselEname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.direction
	 * @return  the value of vessel_info.direction
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getDirection() {
		return direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.direction
	 * @param direction  the value for vessel_info.direction
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setDirection(String direction) {
		this.direction = direction;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.terminal
	 * @return  the value of vessel_info.terminal
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getTerminal() {
		return terminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.terminal
	 * @param terminal  the value for vessel_info.terminal
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setTerminal(String terminal) {
		this.terminal = terminal;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.arrival_time
	 * @return  the value of vessel_info.arrival_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getArrivalTime() {
		return arrivalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.arrival_time
	 * @param arrivalTime  the value for vessel_info.arrival_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setArrivalTime(String arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.voyage
	 * @return  the value of vessel_info.voyage
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getVoyage() {
		return voyage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.voyage
	 * @param voyage  the value for vessel_info.voyage
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setVoyage(String voyage) {
		this.voyage = voyage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column vessel_info.sailing_time
	 * @return  the value of vessel_info.sailing_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public String getSailingTime() {
		return sailingTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column vessel_info.sailing_time
	 * @param sailingTime  the value for vessel_info.sailing_time
	 * @mbg.generated  Wed Mar 22 11:33:53 CST 2017
	 */
	public void setSailingTime(String sailingTime) {
		this.sailingTime = sailingTime;
	}
}