# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-23 16:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ftp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('extra_params', jsonfield.fields.JSONCharField(help_text='JSON object for storing service params value', max_length=4096)),
                ('username', models.CharField(max_length=32, verbose_name='username')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('host', models.CharField(max_length=32, verbose_name='host')),
                ('port', models.PositiveIntegerField(verbose_name='port')),
                ('path', models.CharField(max_length=255, verbose_name='file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenericService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('extra_params', jsonfield.fields.JSONCharField(help_text='JSON object for storing service params value', max_length=4096)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceSchema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code for communication between different systems', max_length=128, verbose_name='code')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('extra_schema', jsonfield.fields.JSONField(help_text='JSON schema for detailing service params')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='genericservice',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='ftp',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='serviceschema',
            unique_together=set([('code',)]),
        ),
    ]
