# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-24 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp',
            name='extra_schema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceSchema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genericservice',
            name='extra_schema',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='service.ServiceSchema'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ftp',
            name='extra_params',
            field=jsonfield.fields.JSONCharField(blank=True, help_text='JSON object for storing service params value', max_length=4096),
        ),
        migrations.AlterField(
            model_name='genericservice',
            name='extra_params',
            field=jsonfield.fields.JSONCharField(blank=True, help_text='JSON object for storing service params value', max_length=4096),
        ),
        migrations.AlterField(
            model_name='serviceschema',
            name='extra_schema',
            field=jsonfield.fields.JSONField(blank=True, help_text='JSON schema for detailing service params'),
        ),
    ]
