# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-03 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('service', '0002_add_schema_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftp',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='customer.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ftp',
            name='mode',
            field=models.SmallIntegerField(choices=[(0, 'Passive'), (1, 'Active')], default=0, verbose_name='mode'),
        ),
        migrations.AddField(
            model_name='ftp',
            name='ssl',
            field=models.BooleanField(default=False, verbose_name='ssl'),
        ),
    ]
