# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('service', '0003_add_ftp_customer_mode_ssl'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('extra_params', jsonfield.fields.JSONCharField(blank=True, help_text='JSON object for storing service params value', max_length=4096)),
                ('src_format', models.CharField(max_length=16, verbose_name='src_format')),
                ('dest_format', models.CharField(max_length=16, verbose_name='dest_format')),
                ('filename', models.CharField(max_length=128, verbose_name='filename')),
                ('extra_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceSchema')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_protocols', to='customer.Customer')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_protocols', to='customer.Customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name', max_length=128, verbose_name='name')),
                ('extra_params', jsonfield.fields.JSONCharField(blank=True, help_text='JSON object for storing service params value', max_length=4096)),
                ('filename', models.CharField(max_length=128, verbose_name='filename')),
                ('extra_schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.ServiceSchema')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='template',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='protocol',
            unique_together=set([('name',)]),
        ),
    ]
