# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-07 08:35
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DbBasedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=128, verbose_name='filename')),
                ('content', common.fields.XBinaryField(verbose_name='content')),
                ('size', models.PositiveIntegerField(verbose_name='size')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dbbasedfile',
            unique_together=set([('filename',)]),
        ),
    ]
