---
# tasks file for ansible-role-gradle

- block:
  - shell: "gradle -v | grep {{ gradle_version }}"
  - debug: msg=" Gradle {{ gradle_version }} is installed"

  rescue:
  - name: "Install unzip"
    apt: name=unzip state=latest

  - name: "Download Gradle {{ gradle_version }}"
    get_url:
      dest: /tmp
      url: "{{ gradle_download_url }}"

  - name: "Extract Gradle"
    shell: "unzip /tmp/{{ gradle_binary }} -d {{ gradle_base_dir }}"

  - name: "Add gradle symlink to path"
    file:
      src: "{{ gradle_base_dir }}/{{ gradle_extract_dir }}/bin/gradle"
      dest: "{{ gradle_link }}"
      owner: root
      group: root
      state: link

  - name: "Validate Gradle version"
    shell: "gradle -v | grep {{ gradle_version }}"
    register: gradle_ver

  - fail:
      msg: "Seems to be gradle {{ gradle_version }} is missing ... aborting"
    when: gradle_ver.rc != 0




